function [alpha,Dalppha,DDalpha] = getALPHAs(phi)
%getALPHAs
%    [ALPHA,Dalppha,DDalpha] = getALPHAs(PHI)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    05-Nov-2023 12:30:34

t2 = DDDdelta(phi);
t3 = DDdelta(phi);
t4 = Ddelta(phi);
t5 = cos(phi);
t6 = delta(phi);
t7 = sin(phi);
alpha = atan(-(t4.*t5-t6.*t7)./(t4.*t7+t5.*t6));
if nargout > 1
    t8 = t4.^2;
    t9 = t4.^3;
    t10 = t6.^2;
    t11 = t8+t10;
    Dalppha = (t8+t11-t3.*t6)./t11;
end
if nargout > 2
    DDalpha = -1.0./t11.^2.*(t3.*t9+t6.*t9.*2.0+t2.*t6.^3-t3.^2.*t4.*t6.*2.0+t2.*t6.*t8-t3.*t4.*t10.*3.0);
end
