function [g,Dg,DDg] = getGs(phi,R)
%getGs
%    [G,Dg,DDg] = getGs(PHI,R)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    05-Nov-2023 12:31:17

t2 = DDalpha(phi);
t3 = Dalpha(phi);
t4 = Ddelta(phi);
t5 = alpha(phi);
t6 = delta(phi);
g = atan((R.*sin(t5)+t6.*sin(phi))./(R.*cos(t5)+t6.*cos(phi)));
if nargout > 1
    t7 = R.^2;
    t8 = t6.^2;
    t9 = -t5;
    t10 = t3.*t7;
    t11 = t4.*t6.*2.0;
    t12 = phi+t9;
    t13 = cos(t12);
    t14 = sin(t12);
    t15 = R.*t4.*t14;
    t16 = R.*t6.*t13;
    t17 = R.*t4.*t13.*2.0;
    t18 = t16.*2.0;
    t19 = t3.*t16;
    t20 = t7+t8+t18;
    t22 = t8+t10+t15+t16+t19;
    t21 = 1.0./t20;
    Dg = t21.*t22;
end
if nargout > 2
    DDg = t21.*(t11+t17+t2.*t7+t2.*t16-R.*t6.*t14+R.*t14.*DDdelta(phi)+R.*t3.^2.*t6.*t14)-t21.^2.*t22.*(t11+t17+R.*t6.*t14.*(t3-1.0).*2.0);
end
